add function to check whether the newly produced epub validates

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,6 +2,18 @@
 
 set -eu
 
+FORCE_CHECK=0
+
+for arg in "$@"
+do
+    case $arg in
+        -c|--check)
+            FORCE_CHECK=1
+            shift
+            ;;
+    esac
+done
+
 book_name=$1
 source_dir=$(mktemp -d -t obp-epub-fixup-src-XXXXXX)
 target_dir=$(mktemp -d -t obp-epub-fixup-trg-XXXXXX)
@@ -13,6 +25,19 @@ cleanup () {
 }
 
 trap cleanup EXIT
+
+check_epub () {
+    epubcheck -q ${book_name}_new.epub &> ${book_name}_new.log
+    local err=$?
+
+    if [ $err -ne 0 ]; then
+	echo "[ERROR] Epubckeck reported errors, ${book_name}_new.log produced"
+
+    elif [ $err -eq 0 ] && [ -f ${book_name}_new.log ]; then
+	echo "[WARNING] Epubcheck issued warning messages, ${book_name}_new.log produced"
+
+    fi
+}
 
 pack_epub () {
     cd ${target_dir}
@@ -46,3 +71,8 @@ echo "Create new epub file"
 
 echo "Copy epub file back"
 cp ${target_dir}/${book_name}_new.epub .
+
+if [ $FORCE_CHECK -eq 1 ]; then
+    echo "Check epub for errors"
+    check_epub
+fi
